east_asia=['China','Japan','Republic of Korea','Mongolia',"Democratic People's Republic of Korea"] 
south_asia=['Afghanistan','Bangladesh','Bhutan','India','Sri Lanka','Maldives','Nepal','Pakistan']
south_east_asia=['Brunei Darussalam','Indonesia','Cambodia','Myanmar','Malaysia','Philippines','Singapore','Thailand','Timor-Leste','Viet Nam']
western_asia=['United Arab Emirates','Azerbaijan','Cyprus','Georgia','Iran','Iraq','Jordan','Kuwait','Lebanon','Oman','State of Pakestine','Qatar','Saudi Arabia','Syrian Arab Republic','Turkey','Yemen']
caucasus_n_central_asia=['Armenia','Azerbaijan','Georgia','Kazakhstan','Kyrgyztan','Tajukistan','Turkmenistan','Uzbekistan']
east_asia_exchina=['Japan','Republic of Korea','Mongolia',"Democratic People's Republic of Korea"]
south_asia_exindia=['Afghanistan','Bangladesh','Bhutan','Sri Lanka','Maldives','Nepal','Pakistan']